---
title: "Portfolio 4"
author: "Ben Hardin"
date: "2023-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R

```{r data}
library(tidyverse)

honesty <- read.csv("data/Honesty Goals data (Deidentified).csv")

#Turning -99 into missing data
honesty <- honesty %>% 
  mutate_all(~replace(., . == -99, NA))

#Creating a new filtered data set
honesty_partners_clean <- honesty %>%
  filter(inclusionsuggestion < 2, validID == 0, partner_interaction == 1)
```

```{r centering}
#within-person means
honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal2_mean = mean(A_goal2, na.rm = T))

#centered goals
honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal2_centered = A_goal2 - A_goal2_mean)

honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal7_mean = mean(A_goal7, na.rm = T))

#centered goals
honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal7_centered = A_goal7 - A_goal7_mean)
```

```{r mlm}
library(lme4)

result <- lmer(A_statehonesty ~ A_goal2_centered + (1 | ID), data = honesty_partners_clean)

summary(result)
```

```{r plot}
ggplot(honesty_partners_clean, aes(x = A_goal2_centered, y = A_statehonesty))+
  geom_point(position = "jitter")+
  geom_smooth(color = "blue")
```

```{r plot-2}
ggplot(honesty_partners_clean, aes(x = A_goal2_centered, y = A_statehonesty))+
  stat_smooth(method = "lm", se = F, geom = "line", linewidth = 0.6, alpha = 0.4, color = "#6699FF", aes(group = ID))+
  geom_smooth(method = "lm", color = "black")+
  theme_classic()+
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.6)+
  scale_y_continuous(
    limits = c(1, 4.3),
    expand = c(0, 0)
    )+
  scale_x_continuous(
    limits = c(-3, 3),
    expand = c(0, 0)
    )+
  labs(title = "Within-person contingencies between honesty and avoiding disapproval",
       x = "How much were you trying to avoid your partner's disapproval?",
       y = "State Honesty")
```

```{r respect}
ggplot(honesty_partners_clean, aes(x = A_goal7_centered, y = A_statehonesty))+
  geom_smooth(method = "lm", se = F, aes(group = ID), color = "skyblue")+
  geom_smooth(method = "lm", color = "black")+
  theme_classic()+
  scale_y_continuous(
    limits = c(1, 4.3),
    expand = c(0, 0)
    )+
  scale_x_continuous(
    limits = c(-3, 3),
    expand = c(0, 0)
    )
```

```{r respect-2}
ggplot(honesty_partners_clean, aes(x = A_goal7_centered, y = A_statehonesty))+
  stat_smooth(method = "lm", se = F, geom = "line", linewidth = 0.6, alpha = 0.4, color = "#6699FF", aes(group = ID))+
  geom_smooth(method = "lm", color = "black")+
  theme_classic()+
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.6)+
  scale_y_continuous(
    limits = c(1, 4.3),
    expand = c(0, 0)
    )+
  scale_x_continuous(
    limits = c(-3, 3),
    expand = c(0, 0)
    )+
  labs(title = "Within-person contingencies between honesty and respect",
       x = "How much were you trying to treat your partner with respect?",
       y = "State Honesty")
```

```{r more-centered}
honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal6_mean = mean(A_goal6, na.rm = T))

#centered goals
honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal6_centered = A_goal6 - A_goal6_mean)

honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal8_mean = mean(A_goal8, na.rm = T))

#centered goals
honesty_partners_clean <- honesty_partners_clean %>%
  group_by(ID) %>%
  mutate(A_goal8_centered = A_goal8 - A_goal8_mean)
```

```{r feelings}
ggplot(honesty_partners_clean, aes(x = A_goal6_centered, y = A_statehonesty))+
  stat_smooth(method = "lm", se = F, geom = "line", linewidth = 0.6, alpha = 0.4, color = "#6699FF", aes(group = ID))+
  geom_smooth(method = "lm", color = "black")+
  theme_classic()+
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.6)+
  scale_y_continuous(
    limits = c(1, 4.3),
    expand = c(0, 0)
    )+
  scale_x_continuous(
    limits = c(-3, 3),
    expand = c(0, 0)
    )
```

```{r caught}
ggplot(honesty_partners_clean, aes(x = A_goal8_centered, y = A_statehonesty))+
  stat_smooth(method = "lm", se = F, geom = "line", linewidth = 0.6, alpha = 0.4, color = "#6699FF", aes(group = ID))+
  geom_smooth(method = "lm", color = "black")+
  theme_classic()+
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.6)+
  scale_y_continuous(
    limits = c(1, 4.3),
    expand = c(0, 0)
    )+
  scale_x_continuous(
    limits = c(-3, 3),
    expand = c(0, 0)
    )
```

```{r make-combined-benefit}
honesty_partners_clean <- honesty_partners_clean %>%
  mutate(combined_benefit = round((A_benefitself + A_benefitpartner)/2))
```

```{r conditioning}
yes_benefit <- honesty_partners_clean %>%
  filter(combined_benefit > 1)

no_benefit <- honesty_partners_clean %>%
  filter(combined_benefit == 1)

ggplot()+
  stat_smooth(data = yes_benefit, method = "lm", se = F, geom = "line", linewidth = 0.6, alpha = 0.4, color = "#6699FF", aes(group = ID, x = A_goal2_centered, y = A_statehonesty))+
  geom_smooth(data = no_benefit, aes(x = A_goal2_centered, y = A_statehonesty), method = "lm", color = "blue3", linetype = "dashed", linewidth = 1.5, alpha = 0.3)+
  geom_smooth(data = yes_benefit, aes(x = A_goal2_centered, y = A_statehonesty), method = "lm", color = "navy", linewidth = 1.5, alpha = 0.3)+
  theme_classic()+
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.6)+
  scale_y_continuous(
    limits = c(1, 4.3),
    expand = c(0, 0)
    )+
  scale_x_continuous(
    limits = c(-3, 3),
    expand = c(0, 0)
    )+
  labs(title = "Within-person contingencies between honesty and avoiding disapproval",
       x = "How much were you trying to avoid your partner's disapproval?",
       y = "State Honesty")
```

```{r ok}
ggplot()+
  stat_smooth(data = yes_benefit, method = "lm", se = F, geom = "line", linewidth = 0.6, alpha = 0.4, color = "#6699FF", aes(group = ID, x = A_goal7_centered, y = A_statehonesty))+
  stat_smooth(data = no_benefit, method = "lm", se = F, geom = "line", linewidth = 0.6, linetype = "dashed", alpha = 0.4, color = "skyblue", aes(group = ID, x = A_goal7_centered, y = A_statehonesty))+
  geom_smooth(data = no_benefit, aes(x = A_goal7_centered, y = A_statehonesty), method = "lm", color = "blue3", linetype = "dashed", linewidth = 1.5, alpha = 0.3)+
  geom_smooth(data = yes_benefit, aes(x = A_goal7_centered, y = A_statehonesty), method = "lm", color = "navy", linewidth = 1.5, alpha = 0.3)+
  theme_classic()+
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.6)+
  scale_y_continuous(
    limits = c(1, 4.3),
    expand = c(0, 0)
    )+
  scale_x_continuous(
    limits = c(-3, 3),
    expand = c(0, 0)
    )
```